# Generated by Django 4.1.7 on 2023-03-30 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='boss_esp',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='esp.esp'),
        ),
    ]
