# Generated by Django 4.2 on 2023-05-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0003_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp',
            name='is_connected',
            field=models.BooleanField(default=False),
        ),
    ]
