# Generated by Django 4.2 on 2023-05-13 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0003_alter_esp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esp',
            name='user',
        ),
    ]
