# Generated by Django 4.2 on 2023-06-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0006_timeranger'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='time_range',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='esp.timeranger'),
        ),
    ]
