# Generated by Django 4.2 on 2023-06-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0007_key_time_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='time_range',
        ),
        migrations.AddField(
            model_name='key',
            name='end_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='start_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='use_time_range',
            field=models.BooleanField(default=False),
        ),
    ]
