# Generated by Django 4.2 on 2023-06-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0008_remove_key_time_range_key_end_time_key_start_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeRanger',
        ),
    ]
