# Generated by Django 4.2.1 on 2023-06-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0010_sensor_motionsensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('MotionSensor', 'MotionSensor')], max_length=55),
        ),
    ]
