# Generated by Django 4.2.1 on 2023-07-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp', '0017_alter_sensor_sensor_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensor',
            new_name='SensorModel',
        ),
    ]
