# Generated by Django 4.2.7 on 2023-12-27 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSocketConsumerAccessesModel',
            fields=[
                ('accesses_create_time', models.DateTimeField(auto_created=True)),
                ('socket_connection_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('socket_disconnect_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('accesses_token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
