# Generated by Django 4.2.7 on 2023-12-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websocketconsumeraccessesmodel',
            name='accesses_create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
