# Generated by Django 4.2.7 on 2023-12-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_alter_websocketconsumeraccessesmodel_accesses_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websocketconsumeraccessesmodel',
            name='socket_connection_time',
        ),
        migrations.RemoveField(
            model_name='websocketconsumeraccessesmodel',
            name='socket_disconnect_time',
        ),
    ]
